services:
  - type: web
    name: shreenovatech-api
    runtime: node
    rootDir: node-backend
    buildCommand: npm install --production
    startCommand: node src/server.js
    plan: free
    region: singapore
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_EXPIRES_IN
        value: 24h
